"""Localized configuration guide; technical prompt and commands stay English."""

from __future__ import annotations

import html
from pathlib import Path

from favicon import FAVICON_TAG, LOGO_IMG
from source_discovery import doctor_report


EN = {
    "title": "AI Subscription Usage: Configuration and User Guide", "intro": "This tool reads local AI usage records and calculates the last 30 days of API-equivalent value, subscription cost, and value multiple. No AI API is required.",
    "start": "First use", "start_body": "Choose Refresh now. The app checks known local directories and reports missing records, permissions, or unsupported formats.",
    "sources": "Data sources", "sources_body": "ChatGPT uses internal Codex JSONL; Claude uses Claude JSONL; Gemini CLI uses chat JSON. Antigravity and Grok are detected separately.",
    "ai": "Configure with your local AI", "ai_body": "Give the English setup prompt below to a local AI. It may only run read-only diagnostics and validated configuration commands.",
    "security": "Security boundary", "security_body": "OAuth, auth tokens, cookies, Keychain, and conversation content are never read.",
    "pricing": "Pricing and calculation", "pricing_body": "Regular input, cache reads, cache writes, and output use separate rates. Unknown models remain unpriced.",
    "trouble": "Troubleshooting", "trouble_body": "Run the doctor when data is missing. Each source reports an explicit status.",
    "commands": "Diagnostic and configuration commands", "detection": "Current detection", "detection_note": "This table is generated on this computer and stays in the current user's data directory. It is not included in public release packages.",
    "provider": "Provider", "surface": "Surface", "status": "Status", "files": "Record files", "prompt": "Prompt for your local AI", "version": "Version",
}

TEXT = {
    "en": EN,
    "zh-CN": {**EN, "title":"AI 订阅用量：配置及使用说明", "intro":"本工具读取本机 AI 用量记录，计算最近 30 天 API 等价价值、订阅成本和价值倍数。计算不需要 AI API。", "start":"首次使用", "start_body":"打开应用后选择“立即更新”。程序检查已知本机目录，并明确显示没有记录、权限不足或格式不支持。", "sources":"数据来源", "sources_body":"ChatGPT 使用内部 Codex JSONL；Claude 使用 Claude JSONL；Gemini CLI 使用聊天 JSON。Antigravity 和 Grok 单独检测。", "ai":"使用本机 AI 帮助配置", "ai_body":"把下方英文配置提示词交给本机 AI。AI 只能执行只读诊断和经过校验的配置命令。", "security":"安全边界", "security_body":"程序不读取 OAuth、Auth Token、Cookie、钥匙串或对话正文。", "pricing":"价格与计算", "pricing_body":"普通输入、缓存读取、缓存写入和输出分别使用对应单价。未知模型不计算金额。", "trouble":"故障排查", "trouble_body":"缺少数据时运行诊断，每个数据源都会显示明确状态。", "commands":"诊断与配置命令", "detection":"本机检测结果", "detection_note":"此表在当前电脑上实时生成，只保存在当前用户的数据目录中，不会包含在通用发布包中。", "provider":"平台", "surface":"使用端", "status":"状态", "files":"记录文件", "prompt":"复制给本机 AI 的配置提示词", "version":"版本"},
    "ja": {**EN, "title":"AIサブスクリプション使用量：設定・使用ガイド", "intro":"ローカルAI使用記録から直近30日間のAPI相当額、費用、価値倍率を計算します。AI APIは不要です。", "start":"初回使用", "start_body":"「今すぐ更新」を選択すると既知のローカルフォルダと状態を確認します。", "sources":"データソース", "sources_body":"ChatGPTはCodex JSONL、ClaudeはClaude JSONL、Gemini CLIはチャットJSONを使用します。AntigravityとGrokは別に検出します。", "ai":"ローカルAIによる設定", "ai_body":"下の英語プロンプトをローカルAIに渡します。読み取り専用診断と検証済み設定だけを実行できます。", "security":"セキュリティ境界", "security_body":"OAuth、Auth Token、Cookie、キーチェーン、会話本文は読み取りません。", "pricing":"価格と計算", "pricing_body":"通常入力、キャッシュ読み取り、キャッシュ書き込み、出力を別々の単価で計算します。", "trouble":"トラブルシューティング", "trouble_body":"データがない場合は診断を実行し、各ソースの状態を確認します。", "commands":"診断・設定コマンド", "detection":"現在の検出結果", "detection_note":"この表は現在の端末で生成され、ユーザーのデータフォルダだけに保存されます。公開パッケージには含まれません。", "provider":"サービス", "surface":"利用形態", "status":"状態", "files":"記録ファイル", "prompt":"ローカルAIに渡すプロンプト", "version":"バージョン"},
    "ko": {**EN, "title":"AI 구독 사용량: 구성 및 사용 안내", "intro":"로컬 AI 사용 기록으로 최근 30일 API 환산 가치, 구독 비용 및 가치 배수를 계산합니다. AI API는 필요하지 않습니다.", "start":"처음 사용", "start_body":"‘지금 업데이트’를 선택하면 알려진 로컬 폴더와 상태를 확인합니다.", "sources":"데이터 소스", "sources_body":"ChatGPT는 Codex JSONL, Claude는 Claude JSONL, Gemini CLI는 채팅 JSON을 사용합니다. Antigravity와 Grok은 별도로 감지합니다.", "ai":"로컬 AI로 구성", "ai_body":"아래 영어 프롬프트를 로컬 AI에 전달합니다. 읽기 전용 진단과 검증된 구성만 실행할 수 있습니다.", "security":"보안 범위", "security_body":"OAuth, Auth Token, Cookie, 키체인 또는 대화 본문을 읽지 않습니다.", "pricing":"가격 및 계산", "pricing_body":"일반 입력, 캐시 읽기, 캐시 쓰기 및 출력은 각각의 단가로 계산합니다.", "trouble":"문제 해결", "trouble_body":"데이터가 없으면 진단을 실행하여 각 소스의 상태를 확인합니다.", "commands":"진단 및 구성 명령", "detection":"현재 감지 결과", "detection_note":"이 표는 현재 컴퓨터에서 생성되어 사용자 데이터 폴더에만 저장됩니다. 공개 패키지에는 포함되지 않습니다.", "provider":"서비스", "surface":"사용 환경", "status":"상태", "files":"기록 파일", "prompt":"로컬 AI에 전달할 프롬프트", "version":"버전"},
    "fr": {**EN, "title":"Utilisation des abonnements IA : configuration et guide", "intro":"Cet outil calcule sur 30 jours la valeur API, le coût et le multiple à partir des journaux locaux. Aucune API d’IA n’est requise.", "start":"Première utilisation", "start_body":"Choisissez Actualiser pour vérifier les dossiers et leur état.", "sources":"Sources de données", "sources_body":"ChatGPT utilise Codex JSONL, Claude utilise Claude JSONL et Gemini CLI utilise le JSON de conversation. Antigravity et Grok sont détectés séparément.", "ai":"Configurer avec votre IA locale", "ai_body":"Donnez l’invite anglaise ci-dessous à votre IA locale. Seuls le diagnostic en lecture seule et la configuration validée sont autorisés.", "security":"Limites de sécurité", "security_body":"OAuth, Auth Token, cookies, Trousseau et contenu des conversations ne sont jamais lus.", "pricing":"Tarifs et calcul", "pricing_body":"Entrées normales, lectures de cache, écritures de cache et sorties utilisent des tarifs distincts.", "trouble":"Dépannage", "trouble_body":"Exécutez le diagnostic et consultez l’état de chaque source.", "commands":"Commandes de diagnostic et de configuration", "detection":"Détection actuelle", "detection_note":"Ce tableau est généré sur cet ordinateur et reste dans le dossier de données de l’utilisateur. Il n’est pas inclus dans les versions publiques.", "provider":"Fournisseur", "surface":"Interface", "status":"État", "files":"Fichiers de données", "prompt":"Invite pour votre IA locale", "version":"Version"},
    "de": {**EN, "title":"KI-Abonnementnutzung: Konfiguration und Anleitung", "intro":"Dieses Tool berechnet aus lokalen Protokollen den API-Gegenwert, die Abokosten und den Wertfaktor der letzten 30 Tage. Keine KI-API ist nötig.", "start":"Erste Verwendung", "start_body":"Jetzt aktualisieren prüft bekannte Ordner und deren Status.", "sources":"Datenquellen", "sources_body":"ChatGPT nutzt Codex JSONL, Claude nutzt Claude JSONL und Gemini CLI nutzt Chat-JSON. Antigravity und Grok werden getrennt erkannt.", "ai":"Mit lokaler KI konfigurieren", "ai_body":"Geben Sie den englischen Prompt unten an Ihre lokale KI. Nur Lesediagnose und validierte Konfiguration sind erlaubt.", "security":"Sicherheitsgrenze", "security_body":"OAuth, Auth Token, Cookies, Schlüsselbund und Gesprächsinhalte werden nie gelesen.", "pricing":"Preise und Berechnung", "pricing_body":"Normale Eingabe, Cache-Lesen, Cache-Schreiben und Ausgabe werden getrennt berechnet.", "trouble":"Fehlerbehebung", "trouble_body":"Führen Sie die Diagnose aus und prüfen Sie den Status jeder Quelle.", "commands":"Diagnose- und Konfigurationsbefehle", "detection":"Aktuelle Erkennung", "detection_note":"Diese Tabelle wird auf diesem Computer erzeugt und nur im Benutzerdatenordner gespeichert. Öffentliche Pakete enthalten sie nicht.", "provider":"Anbieter", "surface":"Oberfläche", "status":"Status", "files":"Datendateien", "prompt":"Prompt für Ihre lokale KI", "version":"Version"},
    "es": {**EN, "title":"Uso de suscripciones de IA: configuración y guía", "intro":"Esta herramienta calcula durante 30 días el valor API, el coste y el múltiplo mediante registros locales. No necesita una API de IA.", "start":"Primer uso", "start_body":"Actualizar ahora revisa directorios conocidos y su estado.", "sources":"Fuentes de datos", "sources_body":"ChatGPT usa Codex JSONL, Claude usa Claude JSONL y Gemini CLI usa JSON de chat. Antigravity y Grok se detectan por separado.", "ai":"Configurar con su IA local", "ai_body":"Entregue el prompt en inglés siguiente a su IA local. Solo se permiten diagnóstico de lectura y configuración validada.", "security":"Límite de seguridad", "security_body":"Nunca se leen OAuth, Auth Token, cookies, Llavero ni contenido de conversaciones.", "pricing":"Precios y cálculo", "pricing_body":"Entrada normal, lectura de caché, escritura de caché y salida usan precios separados.", "trouble":"Solución de problemas", "trouble_body":"Ejecute el diagnóstico y consulte el estado de cada fuente.", "commands":"Comandos de diagnóstico y configuración", "detection":"Detección actual", "detection_note":"Esta tabla se genera en este equipo y solo se guarda en la carpeta de datos del usuario. No se incluye en paquetes públicos.", "provider":"Proveedor", "surface":"Interfaz", "status":"Estado", "files":"Archivos de datos", "prompt":"Prompt para su IA local", "version":"Versión"},
}

AI_PROMPT = "Read the configuration guide for AI Subscription Usage. Run the bundled application with --doctor --json. Do not read OAuth, auth tokens, cookies, Keychain, or conversation content. Do not modify any AI client. If a known source exists outside its default path, use --configure-source with an allowed provider, surface, format, and existing read-only directory. Finish with --verify-sources --json and report only statuses, formats, and file counts."
COMMANDS = "AI Subscription Usage --doctor --json\nAI Subscription Usage --configure-source --provider PROVIDER --surface SURFACE --format FORMAT --path DIRECTORY\nAI Subscription Usage --verify-sources --json\nAI Subscription Usage --refresh"


def render_help(language: str, app_version: str = "development") -> str:
    t = TEXT.get(language, EN)
    rows = "".join(f"<tr><td>{html.escape(x['label'])}</td><td>{html.escape(x['surface'])}</td><td>{html.escape(x['status'])}</td><td>{x['matching_files']}</td></tr>" for x in doctor_report()["discovered_sources"])
    sections = "".join(f"<section><h2>{html.escape(t[key])}</h2><p>{html.escape(t[key + '_body'])}</p></section>" for key in ("start", "sources", "ai", "security", "pricing", "trouble"))
    style = ':root{color-scheme:dark;--bg:#080d18;--card:#101a2b;--ink:#ecf5ff;--sub:#a8b7ce;--line:#263854}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}main{max-width:1100px;margin:auto;padding:38px 24px 72px}h1{font-size:30px;margin:0 0 10px;display:flex;align-items:center;gap:12px}.brand-logo{width:34px;height:34px;border-radius:8px;flex:none}h2{font-size:19px;margin:0 0 8px}p{color:var(--sub);line-height:1.7}section{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:20px;margin-top:16px}pre{white-space:pre-wrap;background:#07101d;border:1px solid var(--line);padding:16px;border-radius:10px;color:#d8eaff}table{width:100%;border-collapse:collapse}th,td{padding:10px;border-top:1px solid var(--line);text-align:left}th{color:var(--sub)}.prompt{user-select:all}'
    script = "let v=0;async function sync(){try{let r=await fetch('http://127.0.0.1:17653/state?ts='+Date.now(),{cache:'no-store'});if(!r.ok)return;let s=await r.json();if(v&&s.report_version!==v&&s.language!==document.documentElement.lang)location.replace('http://127.0.0.1:17653/help?ts='+Date.now());v=s.report_version}catch{}}setInterval(sync,1000);sync();"
    return f'''<!doctype html><html lang="{html.escape(language)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">{FAVICON_TAG}<title>{html.escape(t['title'])}</title><style>{style}</style></head><body><main><h1>{LOGO_IMG}{html.escape(t['title'])}</h1><p>{html.escape(t['intro'])} · Ver {html.escape(app_version)}</p>{sections}<section><h2>{html.escape(t['commands'])}</h2><pre>{html.escape(COMMANDS)}</pre></section><section><h2>{html.escape(t['detection'])}</h2><p>{html.escape(t['detection_note'])}</p><table><thead><tr><th>{html.escape(t['provider'])}</th><th>{html.escape(t['surface'])}</th><th>{html.escape(t['status'])}</th><th>{html.escape(t['files'])}</th></tr></thead><tbody>{rows}</tbody></table></section><section><h2>{html.escape(t['prompt'])}</h2><pre class="prompt">{html.escape(AI_PROMPT)}</pre></section></main><script>{script}</script></body></html>'''


def write_help(path: Path, language: str, app_version: str = "development") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_help(language, app_version), encoding="utf-8")
    return path
